-- MySQL Workbench Synchronization
-- Generated: 2016-01-26 17:02
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Benjamin Hanson

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `dojobyte`.`restaurants` 
DROP COLUMN `hated`,
DROP COLUMN `liked`,
ADD COLUMN `genre` VARCHAR(255) NULL DEFAULT NULL AFTER `restaurant_name`;

ALTER TABLE `dojobyte`.`reviews` 
DROP COLUMN `unhelpful`,
DROP COLUMN `helpful`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
